# AdvancementPicker Configuration

# List of advancements that can be picked
# Format: 'minecraft:advancement_key'
advancements:
  - 'minecraft:story/mine_stone'
  - 'minecraft:story/upgrade_tools'
  - 'minecraft:story/smelt_iron'
  - 'minecraft:story/obtain_armor'
  - 'minecraft:story/lava_bucket'
  - 'minecraft:story/iron_tools'
  - 'minecraft:story/deflect_arrow'
  - 'minecraft:story/form_obsidian'
  - 'minecraft:story/mine_diamond'
  - 'minecraft:story/enter_the_nether'
  - 'minecraft:story/shiny_gear'
  - 'minecraft:story/enchant_item'
  - 'minecraft:story/cure_zombie_villager'
  - 'minecraft:story/follow_ender_eye'
  - 'minecraft:story/enter_the_end'
  - 'minecraft:nether/return_to_sender'
  - 'minecraft:nether/find_bastion'
  - 'minecraft:nether/obtain_ancient_debris'
  - 'minecraft:nether/fast_travel'
  - 'minecraft:nether/find_fortress'
  - 'minecraft:nether/obtain_crying_obsidian'
  - 'minecraft:nether/distract_piglin'
  - 'minecraft:nether/ride_strider'
  - 'minecraft:nether/explore_nether'
  - 'minecraft:nether/brew_potion'
  - 'minecraft:nether/summon_wither'
  - 'minecraft:nether/create_beacon'
  - 'minecraft:nether/create_full_beacon'
  - 'minecraft:nether/all_potions'
  - 'minecraft:nether/all_effects'
  - 'minecraft:nether/netherite_armor'
  - 'minecraft:end/kill_dragon'
  - 'minecraft:end/dragon_egg'
  - 'minecraft:end/enter_end_gateway'
  - 'minecraft:end/respawn_dragon'
  - 'minecraft:end/dragon_breath'
  - 'minecraft:end/find_end_city'
  - 'minecraft:end/elytra'
  - 'minecraft:end/levitate'
  - 'minecraft:adventure/voluntary_exile'
  - 'minecraft:adventure/kill_a_mob'
  - 'minecraft:adventure/trade'
  - 'minecraft:adventure/honey_block_slide'
  - 'minecraft:adventure/sleep_in_bed'
  - 'minecraft:adventure/hero_of_the_village'
  - 'minecraft:adventure/shoot_arrow'
  - 'minecraft:adventure/throw_trident'
  - 'minecraft:adventure/kill_all_mobs'
  - 'minecraft:adventure/totem_of_undying'
  - 'minecraft:adventure/summon_iron_golem'
  - 'minecraft:adventure/two_birds_one_arrow'
  - 'minecraft:adventure/arbalistic'
  - 'minecraft:adventure/adventuring_time'
  - 'minecraft:adventure/very_very_frightening'
  - 'minecraft:adventure/sniper_duel'
  - 'minecraft:adventure/bullseye'

# Human-readable advancement names (optional)
# Format: 'minecraft:advancement_key': 'Human Readable Name'
advancement-names:
  'minecraft:story/mine_stone': '돌 채굴하기'
  'minecraft:story/upgrade_tools': '도구 업그레이드'
  'minecraft:story/smelt_iron': '철 제련하기'
  'minecraft:story/obtain_armor': '갑옷 얻기'
  'minecraft:story/lava_bucket': '용암 양동이'
  'minecraft:story/iron_tools': '철 도구'
  'minecraft:story/deflect_arrow': '화살 막기'
  'minecraft:story/form_obsidian': '흑요석 형성'
  'minecraft:story/mine_diamond': '다이아몬드 채굴하기'
  'minecraft:story/enter_the_nether': '네더 입장'
  'minecraft:story/shiny_gear': '반짝이는 장비'
  'minecraft:story/enchant_item': '아이템 인챈트'
  'minecraft:story/cure_zombie_villager': '좀비 주민 치료하기'
  'minecraft:story/follow_ender_eye': '엔더의 눈 따라가기'
  'minecraft:story/enter_the_end': '엔드 입장'
  'minecraft:nether/return_to_sender': '보낸 사람에게 돌려주기'
  'minecraft:nether/find_bastion': '바스티온 찾기'
  'minecraft:nether/obtain_ancient_debris': '고대 잔해 얻기'
  'minecraft:nether/fast_travel': '빠른 이동'
  'minecraft:nether/find_fortress': '요새 찾기'
  'minecraft:nether/obtain_crying_obsidian': '우는 흑요석 얻기'
  'minecraft:nether/distract_piglin': '피글린 관심 돌리기'
  'minecraft:nether/ride_strider': '스트라이더 타기'
  'minecraft:nether/explore_nether': '네더 탐험'
  'minecraft:nether/brew_potion': '물약 제조'
  'minecraft:nether/summon_wither': '위더 소환'
  'minecraft:nether/create_beacon': '신호기 만들기'
  'minecraft:nether/create_full_beacon': '완전한 신호기 만들기'
  'minecraft:nether/all_potions': '모든 물약'
  'minecraft:nether/all_effects': '모든 효과'
  'minecraft:nether/netherite_armor': '네더라이트 갑옷'
  'minecraft:end/kill_dragon': '드래곤 처치'
  'minecraft:end/dragon_egg': '드래곤 알'
  'minecraft:end/enter_end_gateway': '엔드 관문 들어가기'
  'minecraft:end/respawn_dragon': '드래곤 부활'
  'minecraft:end/dragon_breath': '드래곤의 숨결'
  'minecraft:end/find_end_city': '엔드 도시 찾기'
  'minecraft:end/elytra': '겉날개'
  'minecraft:end/levitate': '공중 부양'
  'minecraft:adventure/voluntary_exile': '자발적 추방'
  'minecraft:adventure/kill_a_mob': '몹 처치'
  'minecraft:adventure/trade': '거래'
  'minecraft:adventure/honey_block_slide': '꿀 블록 미끄러지기'
  'minecraft:adventure/sleep_in_bed': '침대에서 자기'
  'minecraft:adventure/hero_of_the_village': '마을의 영웅'
  'minecraft:adventure/shoot_arrow': '화살 쏘기'
  'minecraft:adventure/throw_trident': '삼지창 던지기'
  'minecraft:adventure/kill_all_mobs': '모든 몹 처치'
  'minecraft:adventure/totem_of_undying': '불사의 토템'
  'minecraft:adventure/summon_iron_golem': '철 골렘 소환'
  'minecraft:adventure/two_birds_one_arrow': '일석이조'
  'minecraft:adventure/arbalistic': '석궁의 달인'
  'minecraft:adventure/adventuring_time': '모험의 시간'
  'minecraft:adventure/very_very_frightening': '매우 매우 무서움'
  'minecraft:adventure/sniper_duel': '스나이퍼 대결'
  'minecraft:adventure/bullseye': '과녁'